<?php
$prize = get_prize($me['id']);
?>
<h2 class="p-2 m-2 text-primary"> <?= cl_translate('Prize manager') ?></h2>
<?php if (@$prize['username'][0]) { ?>
	<div class="table-responsive-md u-datatable px-2" style="padding-bottom: 64px">
		<table id="prizeTable">
			<thead>
				<tr class="text-uppercase font-size-1">
					<th class="font-weight-medium">
						<div class="d-flex justify-content-center align-items-center">
							<input type="checkbox" name="" class="form-check-input" id="selectAll">
						</div>
					</th>
					<th scope="col" class="font-weight-medium">
						<div class="d-flex justify-content-center align-items-center">
							<?= cl_translate('Customer') ?>
							<div class="ml-2">
							</div>
						</div>
					</th>
					<th scope="col" class="font-weight-medium">
						<div class="d-flex justify-content-center align-items-center">
							<?= cl_translate('Store') ?>
							<div class="ml-2">
							</div>
						</div>
					</th>
					<th scope="col" class="font-weight-medium">
						<div class="d-flex justify-content-center align-items-center">
							<?= cl_translate('Event') ?>
							<div class="ml-2">
							</div>
						</div>
					</th>
					<th scope="col" class="font-weight-medium">
						<div class="d-flex justify-content-center align-items-center">
							<?= cl_translate('Prize') ?>
							<div class="ml-2">
							</div>
						</div>
					</th>
					<th scope="col" class="font-weight-medium">
						<div class="d-flex justify-content-center align-items-center">
							<?= cl_translate('Reward') ?>
							<div class="ml-2">
							</div>
						</div>
					</th>
					<th scope="col" class="font-weight-medium">
						<div class="d-flex justify-content-center align-items-center">
							<?= cl_translate('Claimed') ?>
							<div class="ml-2">
							</div>
						</div>
					</th>
					<th scope="col" class="font-weight-medium">
						<div class="d-flex justify-content-center align-items-center">
							<?= cl_translate('Action') ?>
							<div class="ml-2">
							</div>
						</div>
					</th>
				</tr>
			</thead>
			<tbody>
				<?php //foreach ($prize as $p) { 
				?>
				<?php for ($p = 0; $p < count($prize['username']); $p++) { ?>
					<tr class="tr text-center">
						<td>
							<input type="checkbox" class="form-check-input select" data-prize="<?= $prize['id'][$p] ?>" data-id="<?= $me['id'] ?>" data-store="<?= $prize['store_id'][$p] ?>" data-game="<?= $prize['game_id'][$p] ?>">
						</td>
						<td>
							<?= (@$prize['username'])[$p] ? $prize['username'][$p] : $me['name'] ?>
						</td>
						<td class=" text-primary">
							<?= get_store_name($prize['store_id'][$p]) ?>
						</td>
						<td>
							<?= get_game_name($prize['game_id'][$p]) ?>
						</td>
						<td class="text-success">
							<?= $prize['prize'][$p] ?>
						</td>
						<td>
							<?= $date = date('Y-m-d', strtotime($prize['created_at'][$p])) ?>
						</td>
						<td class="text-success claimed">
							<?= ($prize['claimed_at'][$p]) ? date('Y-m-d', strtotime($prize['claimed_at'][$p]))  : '' ?>
						</td>
						<td>
							<div>
								<button class="claim px-3 py-2 border-0 rounded-3 btn-success" data-prize="<?= $prize['id'][$p] ?>" data-id="<?= $me['id'] ?>" data-store="<?= $prize['store_id'][$p] ?>" data-game="<?= $prize['game_id'][$p] ?>"><?php echo cl_icon("trophy-fill"); ?></button>
								<button class="claim-delete px-3 py-2 border-0 rounded-3 btn-danger" data-prize="<?= $prize['id'][$p] ?>" data-id="<?= $me['id'] ?>" data-store="<?= $prize['store_id'][$p] ?>" data-game="<?= $prize['game_id'][$p] ?>"><i class="fas fs-5 fa-trash-alt text-white"></i></button>
							</div>
						</td>
					</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
<?php } else { ?>
	<h4 class="text-danger"><?= cl_translate('No prize available. Try to add store, customer and event') ?></h4>
<?php } ?>