<div class="timeline-placeholder">
	<div class="icon">
		<div class="icon__bg">
			<i class="fas fa-award fs-1"></i>
		</div>
	</div>
	<div class="pl-message">
		<h4>
			<?php echo cl_translate("No Ticket and Prize yet!"); ?>
		</h4>
		<p>
			<?php echo cl_translate("There seems to be you have no ticket and prize yet. All ticket and prize about replies to your store will be displayed here."); ?>
		</p>

	</div>
</div>