<?php
if (@$me['id']) {
    $date = date('Y-m-d');
    // for event
    $get_store = get_store_id($me['id']);
    if (count($get_store) > 0) {
        foreach ($get_store as $s) {
            $get_game[] = get_game_data($s);
        }
        if ($get_game) {
            foreach ($get_game as $get_data) {
                if (count($get_data) > 0) {
                    $id = $get_data['id'];
                    $expires = $get_data['expires_date'];
                    for ($e = 0; $e < count($expires); $e++) {
                        if ($expires[$e]) {
                            $expires_date = date('Y-m-d', strtotime($expires[$e]));
                            if ($date == $expires_date || $date > $expires_date) {
                                $ids = $id[$e];
                                cl_db_update(T_GAME, array('id' => $ids), array('status' => 0));
                            }
                        }
                    }
                }
            }
        }
    }
    //for ticket
    $get_ticket = get_ticket_data($me['id']);
    if (count($get_ticket) > 0) {
        for ($t = 0; $t < count($get_ticket['id']); $t++) {
            $expires_date = date('Y-m-d', strtotime($get_ticket['expires_date'][$t]));
            if ($date == $expires_date || $date > $expires_date) {
                cl_db_update(T_TICKET, array('id' => $get_ticket['id'][$t]), array('ticket' => 0));
            }
        }
    }
}
