<!-- <script type="module">
	import VueGoodTablePlugin from 'vue-good-table';

	import 'vue-good-table/dist/vue-good-table.css'

	Vue.use(VueGoodTablePlugin);

	export default {
		components: {
			VueGoodTable
		},
		// ...
	}
</script> -->
<style>
	.tick {
		padding: 0;
		margin: 0;
		width: 40px;
		height: 40px;
		display: flex;
		align-items: center;
		justify-content: center;
		cursor: pointer;
		border-radius: 100%;
		position: absolute;
		font-size: 20px;
		right: 3%;
		top: 7px;

		color: #06b6f9;
	}

	h6 {
		font-weight: bold;
	}

	.user-name-holder__name {
		color: #0461bf;
	}

	.information-details {
		color: #3d72ab;
	}

	button.btn-custom-icon {
		/* opacity: 0.7; */
		visibility: hidden;
	}

	.notifications-list__item:hover button.btn-custom-icon {
		/* opacity: 1; */
		visibility: visible;
	}

	.notifications-data__body {
		border-bottom: 1px solid var(--cl-primary-border-color);
		transition: all 0.27s ease-in-out;
		padding: var(--cl-primary-offset-size);
		font-size: 14px;

		font-weight: 700;

	}

	.notif-time {
		color: #496389;
	}

	a.disabled {
		pointer-events: none;
		cursor: default;
	}

	select.form-select {
		max-width: 100%;
		height: 52px;
		border: none;
		border-radius: 0px;
		background: var(--cl-input-bg-color);
		border-bottom: 3px solid var(--cl-secondary-border-color);
		box-shadow: none;
		outline: 0;
		font-size: 15px;
		color: var(--cl-primary-text-color);
	}

	option {
		display: block;
		padding: 5px;
		white-space: normal;
		word-wrap: break-word;
		overflow-wrap: break-word;
		max-width: 200px;
	}

	.notifications-data__topline {
		border-right: 1px solid var(--cl-primary-border-color);
		padding: 0 10px;
	}

	.tick:hover {
		background: #a2efa2;
	}
</style>
<div class="timeline-container" data-app="point_system">
	<div class="timeline-header" data-el="tl-header">
		<div class="timeline-header__botline">
			<div class="lp">
				<div class="nav-link-holder">
					<a href="<?php echo cl_link("point_system"); ?>" data-spa="true">
						<?php echo cl_translate("My point system"); ?>
					</a>
				</div>
			</div>
			<div class="cp">
				<a href="<?php echo cl_link('/'); ?>">
					<img src="{%config site_logo%}" alt="Logo">
				</a>
			</div>
			<div class="rp">
				<div class="nav-link-holder">
					<button class="go-options dropleft">
						<div class="dropdown-toggle icon go-options__icon" data-toggle="dropdown">
							<?php echo cl_ficon('more_horiz'); ?>
						</div>
						<div class="dropdown-menu dropdown-icons">
							<!-- <a class="dropdown-item" href="<?php echo cl_link("settings/notifications"); ?>" data-spa="true">
								<span class="flex-item dropdown-item-icon">
									<?php echo cl_ficon('notifications'); ?>
								</span>
								<span class="flex-item">
									<?php echo cl_translate("Notification settings"); ?>
								</span>
								<span class="flex-item dropdown-item-icon dropdown-item-icon_adinfo">
									<?php echo cl_ficon('open'); ?>
								</span>
							</a> -->
							<!-- <?php if (not_empty($cl["notifs"])): ?>
								<div class="dropdown-divider"></div>
								<a onclick="SMColibri.PS.notifs.delete_all_notifs();" class="dropdown-item" href="javascript:void(0);">
									<span class="flex-item dropdown-item-icon">
										<?php echo cl_ficon("delete"); ?>
									</span>
									<span class="flex-item">
										<span><?php echo cl_translate("Delete all notification"); ?></span>
									</span>
								</a>
							<?php endif; ?> -->
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="javascript:void(0);" onclick="SMColibri.go_back();">
								<span class="flex-item dropdown-item-icon">
									<?php echo cl_ficon('arrow_back'); ?>
								</span>
								<span class="flex-item">
									<?php echo cl_translate("Go back"); ?>
								</span>
								<span class="flex-item dropdown-item-icon dropdown-item-icon_adinfo">
									<?php echo cl_ficon('open'); ?>
								</span>
							</a>
						</div>
					</button>
				</div>
			</div>
		</div>
	</div>
	<div class="timeline-navbar">
		<div class="timeline-navbar__item">
			<a href="<?php echo cl_link("point_system"); ?>" data-spa="true">
				<button id='list' class="timeline-navbar__item-btn <?php
																	if ($cl['page_tab'] == 'list') {
																		echo ('active');
																	} ?>">
					<span class="btn-flex-inner">
						<?php echo cl_translate("Distribution list"); ?>
					</span>
				</button>
			</a>
		</div>
		<div class="timeline-navbar__item">
			<a href="<?php echo cl_link("point_new"); ?>" data-spa="true">
				<button class="timeline-navbar__item-btn <?php
															if ($cl['page_tab'] == 'new') {
																echo ('active');
															} ?>">
					<span class="btn-flex-inner">
						<?php echo cl_translate("Point system"); ?>
					</span>
				</button>
			</a>
		</div>

		<div class="timeline-navbar__item">
			<a href="" data-spa="true" class="disabled">
				<button class="timeline-navbar__item-btn <?php if ($cl['page_tab'] == 'edit') {
																echo ('active');
															} ?>">
					<span class="btn-flex-inner">
						<?php echo cl_translate("Edit point system"); ?>
					</span>
				</button>
			</a>
		</div>
	</div>

	<div class="d-block" id="vue-point_system-app" style="padding: 30px;">
		<div class="point_system">
			<?php if ($cl['page_tab'] == 'list'): ?>
				<?php if (not_empty($cl["information"])): ?>
					<div data-an="information-list" class="point_system-list">
						<?php foreach ($cl["information"] as $cl['li']): ?>
							<?php echo cl_template('point_system/includes/list_item'); ?>
						<?php endforeach; ?>
					</div>
				<?php else: ?>
					<?php echo cl_template('point_system/includes/no_notifs'); ?>
				<?php endif; ?>
			<?php elseif ($cl['page_tab'] == 'new'): ?>
				<?php echo cl_template('point_system/includes/create'); ?>
			<?php else: ?>
				<?php if (not_empty($cl["list_distris"])): ?>
					<div data-an="distris-list" class="point_system-list">
						<?php foreach ($cl["list_distris"] as $cl['li']): ?>
							<?php echo cl_template('point_system/includes/list_distris'); ?>
						<?php endforeach; ?>
					</div>
				<?php else: ?>
					<?php echo cl_template('point_system/includes/no_notifs'); ?>
				<?php endif; ?>
			<?php endif; ?>

		</div>
		<?php if (count($cl["information"]) >= 45 && $cl['page_tab'] == 'list'): ?>
			<div class="timeline-data-loader">
				<button v-if="loading" class="timeline-data-loader__btn" disabled="true">
					<?php echo cl_translate("Please wait"); ?>
				</button>
				<button v-else-if="loadmore" class="timeline-data-loader__btn" v-on:click="load_point_system">
					<?php echo cl_translate("Show more"); ?>
				</button>
				<button v-else class="timeline-data-loader__btn" disabled="true">
					<?php echo cl_translate("That is all for now!"); ?>
				</button>
			</div>
		<?php endif; ?>
	</div>
	<?php echo cl_template('point_system/scripts/app_master_script'); ?>
</div>