<link rel="stylesheet" href="https://cdn.datatables.net/2.0.2/css/dataTables.dataTables.min.css">
<script src="https://cdn.datatables.net/2.0.2/js/dataTables.min.js" defer></script>
<?php 
								var_dump();
								die;

?>
<div class="notifications-list__item" data-list-item="<?php //echo ($cl['li']['id']); 
														?>">
	<div class="notif-data">
		<div class="notifications-list__item-data">
			<div class="notifications-data">
				<div class="notifications-data__body">
					<a href="#" data-spa="true">
						<div class="notifications-data__topline">
							<span class="user-name-holder">
								<span class="user-name-holder__name">
									<?php echo $cl['li']['name']; ?>
								</span>

								<?php // if ($cl['li']['verified'] == '1'): 
								?>
								<span class="user-name-holder__badge">
									<?php echo cl_icon("verified_user_badge"); ?>
								</span>
								<?php // endif; 
								?>
							</span>
							<span class="notif-text">
							</span>
						</div>
						<div class="notifications-data__midline">
							<span class="notif-time">
								<?php // echo $cl['li']['time']; 
								?>
							</span>
						</div>
					</a>
				</div>
				<div class="notifications-data__ctrls">
					<div class="notif-ctrls">
						<div class="notif-ctrls__delete">
							<button type="button" class="btn-custom-icon col-red" onclick="SMColibri.PS.notifs.delete_notif(<?php echo ($cl['li']['id']); ?>);">
								<?php echo cl_ficon("delete"); ?>
							</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script>

</script>