<?php
$id = $me['id'];
$sql = "SELECT * FROM cl_store WHERE user_id = $id ORDER BY id DESC";
$result = conn()->query($sql);
?>
<script type="module" src="{%config theme_url%}/statics/js/indexspin.js?v={%config update_date%}"></script>

<div class="timeline-container" data-app="game">
    <div class="timeline-header" data-el="tl-header">
        <div class="timeline-header__botline">
            <div class="lp">
                <div class="nav-link-holder">
                    <a>
                        <?php echo cl_translate("Game"); ?>
                    </a>
                </div>
            </div>
            <div class="cp">
                <a href="<?php echo cl_link('/'); ?>">
                    <img src="{%config site_logo%}" alt="Logo">
                </a>
            </div>
            <div class="rp">
                <div class="nav-link-holder">
                    <span class="go-back" onclick="SMColibri.go_back();">
                        <?php echo cl_ficon('arrow_back'); ?>
                    </span>
                </div>
            </div>
        </div>
    </div>
    <?php //if (not_empty($cl['is_admin'])): 
    ?>
    <!-- Add translate in json -->
    <form action="" class="p-2">
        <h2 class="text-center text-primary">
            <?php echo cl_translate("Add Condition"); ?>
        </h2>
        <div class="d-flex align-items-center justify-content-center">
            <label for="store_id" class="col-2 text-end"><?php echo cl_translate("Select Store:"); ?></label>
            <div class="col-9">
                <select class="form-select store_id m-2 p-2" id="store_id">
                    <?php if ($result->num_rows > 0) {
                        foreach ($result as $row) {
                            $store_id[] = $row['id'];
                            $store_name[] = $row['shop_name']; ?>
                            <option value="<?= $row['id']; ?>"><?= $row['shop_name']; ?></option>
                        <?php } ?>
                    <?php } else { ?>
                        <option value="0"><?php echo cl_translate("No store available, try to add store first"); ?></option>
                </select>
            <?php } ?>
            </div>
        </div>
        <div class="d-flex align-items-center justify-content-center">
            <label for="event" class="col-2 text-end"><?php echo cl_translate("Event Name:"); ?></label>
            <div class="require-event col-9">
                <input type="text" id="event" class="p-2 m-2 form-control" required placeholder="<?php echo cl_translate("Enter Event Name"); ?>">
            </div>
        </div>
        <div class="d-flex align-items-center justify-content-center">
            <label for="buy" class="col-2 text-end"><?php echo cl_translate("Buy:"); ?></label>
            <div class="require-buy col-9">
                <input name="buy" id="buy" class="form-control m-2 p-2" required placeholder="<?php echo cl_translate("Enter minimum Quantity"); ?>">
            </div>
        </div>
        <div class="d-flex align-items-center justify-content-center">
            <label for="limit" class="col-2 text-end"><?php echo cl_translate("Limit:"); ?></label>
            <div class="require-limit col-9">
                <input name="limit" id="limit" class="form-control m-2 p-2" required placeholder="<?php echo cl_translate("Enter minimum price for 1 ticket"); ?>">
            </div>
        </div>
        <div class="d-none align-items-center justify-content-center">
            <label for="quantity" class="col-2 text-end"><?php echo cl_translate("Quantity:"); ?></label>
            <div class="require-quantity col-9">
                <input name="quantity" id="quantity" class="form-control m-2 p-2" placeholder="<?php echo cl_translate("Enter minimum quantity to create ticket"); ?>">
            </div>
        </div>
        <div class="d-flex align-items-center justify-content-center">
            <label for="expires" class="col-2 text-end"><?php echo cl_translate("Expires Date:"); ?></label>
            <div class="require-expires col-9">
                <input name="expires" id="expires" class="form-control m-2 p-2" required placeholder="<?php echo cl_translate("Enter expires date for ticket"); ?>">
            </div>
        </div>
        <div class="d-flex align-items-center justify-content-center">
            <label for="join" class="col-2 text-end"><?php echo cl_translate("Max Ticket:"); ?></label>
            <div class="require-join col-9">
                <input name="join" id="join" class="form-control m-2 p-2" required placeholder="<?php echo cl_translate("Enter max ticket customer can have"); ?>">
            </div>
        </div>
        <div class="text-center">
            <button class="p-2 m-2 px-3 text-white btn-primary border-0 rounded-pill add-condition"><?php echo cl_translate("Add conditions"); ?></button>
        </div>
    </form>

    <form action="" class="p-2">
        <h2 class="text-center text-success">
            <?php echo cl_translate("Add Event"); ?>
        </h2>
        <div class="d-flex align-items-center justify-content-center">
            <label for="prize" class="col-2 text-end"><?php echo cl_translate("Prize:"); ?></label>
            <div class="require-prize col-9">
                <input type="text" id="prize" placeholder="<?php echo cl_translate("Enter Prize"); ?>" data-role="tagsinput" required>
            </div>
        </div>
        <div class="d-flex align-items-center justify-content-center">
            <label for="stock" class="col-2 text-end"><?php echo cl_translate("Stock:"); ?></label>
            <div class="require-stock col-9">
                <input type="text" name="stock" id="stock" placeholder="<?php echo cl_translate("Enter Stock, number only"); ?>" data-role="tagsinput" required>
            </div>
        </div>
        <div class="d-flex align-items-center justify-content-center">
            <label for="percent" class="col-2 text-end"><?php echo cl_translate("Percent:"); ?></label>
            <div class="require-percent col-9">
                <input type="text" name="percent" id="percent" placeholder="<?php echo cl_translate("Enter Percent, number only"); ?>" data-role="tagsinput" required>
            </div>
        </div>
        <div class="d-flex align-items-center justify-content-center">
            <label for="expires-event" class="col-2 text-end"><?php echo cl_translate("Expires Event:"); ?></label>
            <div class="require-expires-event col-9">
                <input type="datetime-local" name="expires-event" id="expires-event" class="form-control m-2 p-2" required>
            </div>
        </div>
        <div class="d-flex align-items-center justify-content-center">
            <label for="status" class="col-2 text-end"><?php echo cl_translate("Status:"); ?></label>
            <div class="col-9">
                <select class="form-select status m-2 p-2" id="status">
                    <option value="0"><?php echo cl_translate("Draft"); ?></option>
                    <option value="1"><?php echo cl_translate("Publish"); ?></option>
                </select>
            </div>
        </div>
        <div class="d-flex align-items-center justify-content-center">
            <label for="themes" class="col-2 text-end"><?php echo cl_translate("Theme:"); ?></label>
            <div class="col-9">
                <select class="form-select themes m-2 p-2" id="themes"></select>
            </div>
        </div>

        <div class="text-center">
            <button class="p-2 px-3 m-2 text-white btn-success border-0 rounded-pill add-prize"><?php echo cl_translate("Add prize"); ?></button>
            <!-- <button class="ml-auto btn btn-custom main-inline lg add-prize"><?php echo cl_translate("Add prize"); ?></button> -->

            <!-- <button class="col-2 p-2 m-2 px-3 text-white btn-danger border-0 rounded-pill clear-prize"><?php echo cl_translate("Clear"); ?></button> -->
        </div>
    </form>

    <div class="d-flex align-items-center justify-content-center">
        <label for="setup" class="col-2 text-end"><?php echo cl_translate("Prize setup:"); ?></label>
        <div class="col-9">
            <select name="setup" id="setup" class="form-select setup m-2 p-2">
                <?php
                for ($i = 0; $i < count($store_id); $i++) {
                    $id = $store_id[$i];
                    $store = $store_name[$i];
                    $sql_draft = "SELECT * FROM cl_game WHERE store_id = $id AND status = 0 ORDER BY id DESC";
                    $result_draft = conn()->query($sql_draft);
                    if ($result_draft->num_rows > 0) {
                        foreach ($result_draft as $row) { ?>
                            <option value="<?= $row['id'] ?>"><?= $store . ': ' . $row['game_name'] ?></option>
                        <?php } ?>
                    <?php } ?>
                <?php } ?>
            </select>
        </div>
    </div>
    <div class="text-center">
        <button class="p-2 m-2 px-3 text-white btn-primary border-0 rounded-pill publish-prize"><?php echo cl_translate("Publish"); ?></button>
    </div>
    <?php //endif; 
    ?>
    <center>
        <?php
        if (@$store_id) {
            foreach ($store_id as $id) {
                $sql_game = "SELECT * FROM cl_game WHERE store_id = $id AND status = 1 ORDER BY id DESC";
            }
            $result_game = conn()->query($sql_game);
        ?>
            <div class="timeline-game">
                <div class="">
                    <div class="">
                        <div>
                            <?php if ($result_game->num_rows > 0) {
                                foreach ($result_game as $row) {
                                    $attr = json_decode($row['props'], true);
                                    $value = choose_prize($attr);
                                    $prize = $value['value'];
                            ?>
                                    <input type="hidden" name="" id="propsWheel" data-prop='<?= $row['props']; ?>' data-themes='<?= $row['themes'] ?>'>
                                    <input type="hidden" id="tokenApi" value="<?= get_random() . $prize . get_random() ?>">
                                <?php } ?>
                            <?php } ?>
                        </div>
                    </div>
                <?php } ?>
                <div class="wheel-wrapper"></div>
                <button id="spin" class="col-4 spin p-2 m-2 btn-primary rounded-pill">
                    <span class="fs-4">Spin</span>
                </button>

                </div>
            </div>
    </center>
</div>
<script src="{%config theme_url%}/statics/tags-input/dist/bootstrap-tagsinput.min.js"> </script>
<?php echo cl_template('game/scripts/app_master_script');
?>