<?php
$prize = get_prize($me['id']);
$store_id = get_store_id($me['id']);
if ($store_id) {
    foreach ($store_id as $s) {
        $game_id = get_game_id($s);
        if ($game_id) {
            foreach ($game_id as $g) {
                $is_owner = is_owner($g);
                $ticket = get_ticket($g);
                $ticket_check[] = get_ticket($g);
                // var_dump($ticket);
                if (@count($ticket) > 0) {
                    $get_ticket[] = $ticket;
                }
            }
        }
    }
} else {
    $is_owner = null;
    $ticket_check = null;
}
?>
<style>
    tbody>.tr:hover {
        background: #e9e9e9 !important;
    }

    .dt-type-date {
        text-align: center !important;
    }

    .dt-input {
        margin: 0 5px !important;
    }

    tbody>tr>td {
        padding: 4px 0 !important;
    }

    tr {
        border-top: 1px solid #ccc;
        border-bottom: 1px solid #ccc;
    }

    .tr:nth-child(odd) {
        background-color: #f4f4f4 !important;
        /* Color for odd rows */
    }

    .tr:nth-child(even) {
        background-color: #ffffff !important;
        /* Color for even rows */
    }
</style>
<div class="timeline-container" data-app="store">
    <div class="timeline-header" data-el="tl-header">
        <div class="timeline-header__botline">
            <div class="lp">
                <div class="nav-link-holder">
                    <a>
                        <?php echo cl_translate("Manager"); ?>
                    </a>
                </div>
            </div>
            <div class="cp">
                <a href="<?php echo cl_link('/'); ?>">
                    <img src="{%config site_logo%}" alt="Logo">
                </a>
            </div>
            <div class="rp">
                <div class="nav-link-holder">
                    <span class="go-back" onclick="SMColibri.go_back();">
                        <?php echo cl_ficon('arrow_back'); ?>
                    </span>
                </div>
            </div>
        </div>
    </div>
    <center>
        <?php //if (not_empty($cl['is_admin'])): 
        ?>
        <!-- Add translate in json -->
        <?php if ($prize || $ticket_check) { ?>
            <?php echo cl_template('manager/includes/list_ticket'); ?>
            <?php echo cl_template('manager/includes/list_item'); ?>
        <?php } else { ?>
            <?php echo cl_template('manager/includes/no_prize'); ?>
        <?php } ?>

        <?php //endif; 
        ?>
    </center>
</div>
<?php echo cl_template('manager/scripts/app_master_script'); ?>
<script src="{%config theme_url%}/statics/DataTables/datatables.min.js"></script>
<script>
    $(document).ready(function() {
        $('#prizeTable').DataTable({
            columnDefs: [{
                    targets: 0,
                    orderable: false
                } // Disable sorting for the first column (index 0)
            ]
        });
        new DataTable('#ticketTable');
    });
</script>