<!-- <link rel="stylesheet" href="https://cdn.datatables.net/2.0.2/css/dataTables.dataTables.min.css">
<script src="https://cdn.datatables.net/2.0.2/js/dataTables.min.js" defer></script> -->

<div class="notifications-list__item" data-list-item="<?php echo ($cl['li']['id']);
														?>">
	<div class="notif-data">
		<div class="notifications-list__item-data">
			<div class="notifications-data">
				<div class="notifications-data__body" style="display: flex;">
					<a href="<?php echo cl_link("edit_distri") . '/' . $cl['li']['id']; ?>" data-spa="true" style="display: flex;">
						<div class="notifications-data__topline">
							<span class="user-name-holder" style="flex-wrap: wrap;">
								<span class="user-name-holder__name">
									<?php echo cl_translate("Select system| "); ?>
									<?php echo cl_translate("Phone") . ': ' . $cl['li']['phone']; ?>

								</span>

								<span class="information-details">
									<?php echo $cl['li']['rewards'] ? ', ' . cl_translate("Rewards") . ': ' . $cl['li']['rewards']. $cl["symbol"] : ''; ?>

								</span>
								<!-- <span class="information-details">
									<?php echo $cl['li']['rewards'] ? ', ' . cl_translate("rewards") . ': ' . $cl['li']['rewards']. $cl["symbol"] : ''; ?>
								</span> -->


							</span>
						</div>
						<div class="notifications-data__midline">
							<span class="notif-time">
								<?php echo $cl['li']['created_at']; ?>
							</span>
						</div>
					</a>
					<!-- <div class="notifications-data__ctrls" style="width:5%">
						<div class="notif-ctrls">
							<div class="notif-ctrls__delete">
								<button type="button" class="btn-custom-icon col-red" onclick="SMColibri.PS.point_system.delete_information(<?php echo ($cl['li']['id']); ?>);">
									<?php echo cl_ficon("delete"); ?>
								</button>
							</div>
						</div>
					</div> -->
				</div>


			</div>
		</div>
	</div>
</div>
<script>

</script>