<script>
	"use strict";

	function getCurrentDate() {
		const now = new Date();

		// Get year, month, and day
		const year = now.getFullYear();
		const month = String(now.getMonth() + 1).padStart(2, '0'); // Months are 0-based
		const day = String(now.getDate()).padStart(2, '0');

		// Combine them into a string in the desired format
		return `${year}-${month}-${day}`;
	}

	// Get and display the formatted date
	const date = getCurrentDate();
	$(document).ready(function($) {
		$("#store").on("input", function(e) {
			var currentValue = $(this).val();
			var required = '<?php echo cl_translate("This field is required"); ?>';
			if (!currentValue) {
				var b = `<b class='text-danger p-2 required-store'>${required}</b>`;
				$('.require-store').append(b);
			} else {
				$('.required-store').remove();
			}
		});
		$("#address").on("input", function(e) {
			var currentValue = $(this).val();
			var required = '<?php echo cl_translate("This field is required"); ?>';
			if (!currentValue) {
				var b = `<b class='text-danger p-2 required-address'>${required}</b>`;
				$('.require-address').append(b);
			} else {
				$('.required-address').remove();
			}
		});
		$("#city").on("input", function(e) {
			var currentValue = $(this).val();
			var required = '<?php echo cl_translate("This field is required"); ?>';
			if (!currentValue) {
				var b = `<b class='text-danger p-2 required-city'>${required}</b>`;
				$('.require-city').append(b);
			} else {
				$('.required-city').remove();
			}
		});
		$("#phone").on("input", function(e) {
			var currentValue = $(this).val();
			var required = '<?php echo cl_translate("This field is required"); ?>';
			if (!currentValue) {
				var b = `<b class='text-danger p-2 required-phone'>${required}</b>`;
				$('.require-phone').append(b);
			} else {
				$('.required-phone').remove();
			}
		});
		$("#mail").on("input", function(e) {
			var currentValue = $(this).val();
			var required = '<?php echo cl_translate("Invalid email format"); ?>';
			var emailPattern = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/;

			if (!emailPattern.test(currentValue)) {
				var b = `<b class='text-danger p-2 required-mail'>${required}</b>`;
				if ($('.required-mail').length == 0) {
					$('.require-mail').append(b);
				}
			} else {
				$('.required-mail').remove();
			}
		});

		$('.add-store').on('click', function(e) {
			e.preventDefault();
			if (!($("#store").val() && $("#address").val() && $("#city").val() && $("#phone").val())) {
				Swal.fire({
					title: "<?php echo cl_translate("Failed"); ?>",
					text: "<?php echo cl_translate("Enter all the field required!"); ?>",
					icon: "error",
					allowOutsideClick: true,
					showConfirmButton: true,
					onBeforeOpen: () => {
						Swal.showLoading();
					},
				});
				return;
			}
			var store = $('#store').val();
			var address = $('#address').val();
			var city = $('#city').val();
			var phone = $('#phone').val();
			var mail = $('#mail').val();
			$.ajax({
				url: '<?php echo cl_link("native_api/store/add_store"); ?>',
				type: 'POST',
				data: {
					store: store,
					address: address,
					city: city,
					phone: phone,
					mail: mail
				},
				success: function(result) {
					if (result.status == 200) {
						Swal.fire({
							title: "<?php echo cl_translate("Success"); ?>",
							text: "<?php echo cl_translate("Add store success!"); ?>",
							icon: "success",
							allowOutsideClick: true,
							showConfirmButton: true,
							onBeforeOpen: () => {
								Swal.showLoading();
							},
						}).then((response) => {
							if (response.isConfirmed) {
								if ($('.store-tr').length > 0) {
									var tr = `  <tr class="tr text-center">
											<td class="align-middle text-dark font-weight-normal"><b>${store}</b></td>
											<td>
												<span>${address}</span>
											</td>
											<td class="align-middle">${city}</td>
											<td class="align-middle text-success text-center">${phone}</td>
											<td class="align-middle text-primary">${mail}</td>
											<td>
												<div>
													<button class="edit-store text-white border-0 rounded-3 btn-primary" data-id="${result.id}"><i class="fas fs-5 fa-edit text-white"></i></button>
													<button class="delete-store text-white border-0 rounded-3 btn-danger" data-id="${result.id}"><i class="fas fs-5 fa-trash-alt text-white"></i></button>
												</div>
											</td>
										</tr>`
									$('.store-tr').append(tr);
								} else {
									window.location.reload();
								}
							}
						})
					} else if (result.status == 500) {
						Swal.fire({
							title: "<?php echo cl_translate("Warning"); ?>",
							text: "<?php echo cl_translate("Store already exist!"); ?>",
							icon: "warning",
							allowOutsideClick: true,
							showConfirmButton: true,
							onBeforeOpen: () => {
								Swal.showLoading();
							},
						});
					} else {
						Swal.fire({
							title: "<?php echo cl_translate("Failed"); ?>",
							text: "<?php echo cl_translate("Error occurred, check your info before add!"); ?>",
							icon: "Error",
							allowOutsideClick: true,
							showConfirmButton: true,
							onBeforeOpen: () => {
								Swal.showLoading();
							},
						});
					}
				}
			})
		})
		$('.delete').on('click', function() {
			var id = $(this).attr('data-id');
			var tr = $(this).closest('tr');
			Swal.fire({
				title: "<?php echo cl_translate("Warning"); ?>",
				text: "<?php echo cl_translate("Are you certain about deleting event for this store?"); ?>",
				icon: "warning",
				allowOutsideClick: false,
				showConfirmButton: true,
				showCancelButton: true,
				confirmButtonText: "<?php echo cl_translate("Ok"); ?>",
				cancelButtonText: "<?php echo cl_translate("Cancel"); ?>",
				onBeforeOpen: () => {
					Swal.showLoading();
				},
			}).then((response) => {
				if (response.isConfirmed) {
					$.ajax({
						url: "<?php echo cl_link("native_api/store/delete_event"); ?>",
						type: 'POST',
						data: {
							id: id
						},
						success: function(result) {
							if (result.status = 200) {
								Swal.fire({
									title: "<?php echo cl_translate("Success"); ?>",
									text: "<?php echo cl_translate("Delete Event success!"); ?>",
									icon: "success",
									allowOutsideClick: true,
									showConfirmButton: true,
									onBeforeOpen: () => {
										Swal.showLoading();
									},
								});
								tr.fadeOut();
							} else {
								Swal.fire({
									title: "<?php echo cl_translate("Error"); ?>",
									text: "<?php echo cl_translate("Error Ocurred, Delete failed!"); ?>",
									icon: "error",
									allowOutsideClick: true,
									showConfirmButton: true,
									onBeforeOpen: () => {
										Swal.showLoading();
									},
								});
							}
						}
					})
				}
			});
		})
		$(document).on('click', '.delete-store', function() {
			var id = $(this).attr('data-id');
			var tr = $(this).closest('tr');
			Swal.fire({
				title: "<?php echo cl_translate("Warning"); ?>",
				text: "<?php echo cl_translate("Are you certain about deleting this store?"); ?>",
				icon: "warning",
				allowOutsideClick: false,
				showConfirmButton: true,
				showCancelButton: true,
				confirmButtonText: "<?php echo cl_translate("Ok"); ?>",
				cancelButtonText: "<?php echo cl_translate("Cancel"); ?>",
				onBeforeOpen: () => {
					Swal.showLoading();
				},
			}).then((response) => {
				if (response.isConfirmed) {
					$.ajax({
						url: "<?php echo cl_link("native_api/store/delete_store"); ?>",
						type: 'POST',
						data: {
							id: id
						},
						success: function(result) {
							if (result.status = 200) {
								Swal.fire({
									title: "<?php echo cl_translate("Success"); ?>",
									text: "<?php echo cl_translate("Delete Store success!"); ?>",
									icon: "success",
									allowOutsideClick: true,
									showConfirmButton: true,
									onBeforeOpen: () => {
										Swal.showLoading();
									},
								});
								tr.fadeOut();
							} else {
								Swal.fire({
									title: "<?php echo cl_translate("Error"); ?>",
									text: "<?php echo cl_translate("Error Ocurred, Delete failed!"); ?>",
									icon: "error",
									allowOutsideClick: true,
									showConfirmButton: true,
									onBeforeOpen: () => {
										Swal.showLoading();
									},
								});
							}
						}
					})
				}
			});
		})
		$('.edit-store').on('click', function() {
			var id = $(this).attr('data-id');
			var store = $(this).attr('data-store');
			var address = $(this).attr('data-address');
			var city = $(this).attr('data-city');
			var phone = $(this).attr('data-phone');
			var mail = $(this).attr('data-mail');
			$(this).parent().find(".save-store").show();
			$(this).hide();

			var inputStore = `
            <div class='d-flex justify-content-center'>
              <input type='text' class='save-shop form-control' data-id='${id}' value='${store}'>
            </div>`;
			var inputAddress = `
            <div class='d-flex justify-content-center'>
              <input type='text' class='save-address form-control' data-id='${id}' value='${address}'>
            </div>`;
			var inputCity = `
            <div class='d-flex justify-content-center'>
              <input type='text' class='save-city form-control' data-id='${id}' value='${city}'>
            </div>`;
			var inputPhone = `
            <div class='d-flex justify-content-center'>
              <input type='text' class='save-phone form-control' data-id='${id}' value='${phone}'>
            </div>`;
			var inputMail = `
            <div class='d-flex justify-content-center'>
              <input type='text' class='save-mail form-control' data-id='${id}' value='${mail}'>
            </div>`;
			var storeField = $(this).closest("tr").find(".store-field");
			var addressField = $(this).closest("tr").find(".address-field");
			var cityField = $(this).closest("tr").find(".city-field");
			var phoneField = $(this).closest("tr").find(".phone-field");
			var mailField = $(this).closest("tr").find(".mail-field");

			storeField.html(inputStore);
			addressField.html(inputAddress);
			cityField.html(inputCity);
			phoneField.html(inputPhone);
			mailField.html(inputMail);

		})
		$('.save-store').on('click', function() {
			var shop = $(this).closest("tr").find(".save-shop").val();
			var address = $(this).closest("tr").find(".save-address").val();
			var city = $(this).closest("tr").find(".save-city").val();
			var phone = $(this).closest("tr").find(".save-phone").val();
			var mail = $(this).closest("tr").find(".save-mail").val();
			var saveId = $(this).attr("data-id");
			var storeField = $(this).closest("tr").find(".store-field");
			var addressField = $(this).closest("tr").find(".address-field");
			var cityField = $(this).closest("tr").find(".city-field");
			var phoneField = $(this).closest("tr").find(".phone-field");
			var mailField = $(this).closest("tr").find(".mail-field");
			storeField.html(shop);
			addressField.html(address);
			cityField.html(city);
			phoneField.html(phone);
			mailField.html(mail);
			$(this).hide();
			$(this).parent().find(".edit-store").show();
			var saveId = $(this).attr("data-id");

			$.ajax({
				url: "<?php echo cl_link("native_api/store/save_store"); ?>",
				type: 'POST',
				data: {
					id: saveId,
					store: shop,
					address: address,
					city: city,
					phone: phone,
					mail: mail
				},
				success: function(result) {
					Swal.fire({
						title: "<?php echo cl_translate("Success"); ?>",
						text: "<?php echo cl_translate("Save change success!"); ?>",
						icon: "success",
						allowOutsideClick: true,
						showConfirmButton: true,
						onBeforeOpen: () => {
							Swal.showLoading();
						},
					});
				}
			})
		})

		$(document).on('click', '.edit', function() {
			var id = $(this).attr('data-id');
			var event = $(this).attr('data-event');
			var store = $(this).attr('data-store');
			var values = $(this).attr('data-values');
			var prizes = $(this).attr('data-prizes');
			var stocks = $(this).attr('data-stocks');
			var percents = $(this).attr('data-percents');
			var limit = $(this).attr('data-limit');
			var created = $(this).attr('data-created');
			var expires = $(this).attr('data-expires');
			let formattedValue = parseFloat(limit).toLocaleString('en-US', {
				maximumFractionDigits: 2
			});
			var join = $(this).attr('data-join');

			$('#save-id').val(id);
			$('#save-event').val(event);
			$('#save-prize').val(prizes);
			$('#save-stock').val(stocks);
			$('#save-percent').val(percents);
			$('#save-limit').val(formattedValue);
			$('#save-join').val(join);
			$('#save-created').val(created);
			$('#save-expires').val(expires);
			$('#editLabel').html('<?= cl_translate('Edit event ') ?>' + event + ' at ' + store)
			var eventField = $(this).closest("tr").find(".event");
			var limitField = $(this).closest("tr").find(".limit");
			var joinField = $(this).closest("tr").find(".join");
			var prizeField = $(this).closest("tr").find(".prizes");
			var stockField = $(this).closest("tr").find(".stocks");
			var percentField = $(this).closest("tr").find(".percents");
			var createdField = $(this).closest("tr").find(".created");
			var expiresField = $(this).closest("tr").find(".expires");
			var dataEdit = $(this).parent().find(".edit");

			$('#save').off('click').on('click', function() {
				var event = $("#save-event").val();
				var prize = $("#save-prize").val();
				var stock = $("#save-stock").val();
				var percent = $("#save-percent").val();
				var limit = $("#save-limit").val();
				var limitUs = $("#save-limit").val();
				limit = limit.replace(/,/g, '');
				var join = $("#save-join").val();
				//id 
				var saveId = $("#save-id").val();
				var created = $("#save-created").val();
				var expires = $("#save-expires").val();
				// check condition
				var checkPrize = prize.split(', ');
				var checkStock = stock.split(', ');
				var checkPercent = percent.split(', ');
				console.log(expires);
				// Check expires
				if (!expires) {
					Swal.fire({
						title: "<?php echo cl_translate("Failed"); ?>",
						html: "<h5 class='text-danger'><?= cl_translate("Please select the expiration date"); ?> </h5>",
						icon: "error",
						allowOutsideClick: true,
						showConfirmButton: true,
						onBeforeOpen: () => {
							Swal.showLoading();
						},
					});
					return;
				} else if (expires <= date) {
					Swal.fire({
						title: "<?php echo cl_translate("Failed"); ?>",
						html: "<h5 class='text-danger'><?= cl_translate("The expiration date has passed or is today"); ?> </h5>",
						icon: "error",
						allowOutsideClick: true,
						showConfirmButton: true,
						onBeforeOpen: () => {
							Swal.showLoading();
						},
					});
					return;
				}
				if (checkPrize.length !== checkStock.length) {
					Swal.fire({
						title: "<?php echo cl_translate("Failed"); ?>",
						text: "<?php echo cl_translate("Prize, Percent and Stock not match. Please check and try again"); ?>",
						icon: "warning",
						allowOutsideClick: true,
						showConfirmButton: true,
						onBeforeOpen: () => {
							Swal.showLoading();
						},
					});
					return;
				} else if (checkPrize.length !== checkPercent.length) {
					Swal.fire({
						title: "<?php echo cl_translate("Failed"); ?>",
						text: "<?php echo cl_translate("Prize, Percent and Stock not match. Please check and try again"); ?>",
						icon: "warning",
						allowOutsideClick: true,
						showConfirmButton: true,
						onBeforeOpen: () => {
							Swal.showLoading();
						},
					});
					return;
				}
				// check percent
				var arr = percent.split(', ');
				var total = 0;
				for (var p = 0; p < arr.length; p++) {
					total += parseFloat(arr[p]);
					if (parseFloat(arr[p]) < 0.01) {
						Swal.fire({
							title: "<?php echo cl_translate("Warning"); ?>",
							html: "<h4 class='text-danger'><?php echo cl_translate("Percent allow >= 0.01"); ?>: ",
							icon: "error",
							allowOutsideClick: true,
							showConfirmButton: true,
							onBeforeOpen: () => {
								Swal.showLoading();
							},
						});
						return;
					}
				}
				if (total > 100) {
					Swal.fire({
						title: "<?php echo cl_translate("Failed"); ?>",
						html: "<h4 class='text-danger'><?php echo cl_translate("Your Percent"); ?>: " + total + "%</h4>" + " <?php echo cl_translate("Your set up percent > 100%. Please check and try again!"); ?>",
						icon: "error",
						allowOutsideClick: true,
						showConfirmButton: true,
						onBeforeOpen: () => {
							Swal.showLoading();
						},
					});
					return;
				} else if (total < 100) {
					Swal.fire({
						title: "<?php echo cl_translate("Failed"); ?>",
						html: "<h4 class='text-danger'><?php echo cl_translate("Your Percent"); ?>: " + total + "%</h4>" + " <?php echo cl_translate("Your set up percent < 100%. Please check and try again!"); ?>",
						icon: "error",
						allowOutsideClick: true,
						showConfirmButton: true,
						onBeforeOpen: () => {
							Swal.showLoading();
						},
					});
					return;
				}
				// $(this).parent().find(".edit").show();
				// $(this).hide();
				eventField.html(event);
				limitField.html(limitUs);
				joinField.html(join);
				createdField.html(created);
				expiresField.html(expires);
				prizeField.html('Prize: ' + prize);
				stockField.html('Stock: ' + stock);
				percentField.html('Percent: ' + percent);

				dataEdit.attr('data-limit', limit);
				dataEdit.attr('data-join', join);
				dataEdit.attr('data-event', event);
				dataEdit.attr('data-created', created);
				dataEdit.attr('data-expires', expires);
				dataEdit.attr('data-prizes', prize);
				dataEdit.attr('data-stocks', stock);
				dataEdit.attr('data-percents', percent);
				$.ajax({
					url: "<?php echo cl_link("native_api/store/save_event"); ?>",
					type: 'POST',
					data: {
						id: saveId,
						event: event,
						prize: prize,
						stock: stock,
						percent: percent,
						limit: limit,
						join: join,
						created: created,
						expires: expires,
					},
					success: function(result) {
						Swal.fire({
							title: "<?php echo cl_translate("Success"); ?>",
							text: "<?php echo cl_translate("Save change success!"); ?>",
							icon: "success",
							allowOutsideClick: true,
							showConfirmButton: true,
							onBeforeOpen: () => {
								Swal.showLoading();
							},
						});
						$('#edit').modal('hide');
					}
				})
			})
		})
		$('#save-limit').on('input', function() {
			var limit = $(this).val();
			limit = limit.replace(/[^0-9.]/g, '');
			if (limit) {
				let formattedValue = parseFloat(limit).toLocaleString('en-US', {
					maximumFractionDigits: 2,
					minimumFractionDigits: 0
				});
				// Update the input value
				$(this).val(formattedValue);
			}
		});
		$('#save-percent').on('input', function() {
			var percentArray = $(this).val().split(', ');
			var total = percentArray.reduce(function(sum, percent) {
				// Convert to a float and add to the sum
				return sum + (parseFloat(percent.trim()) || 0); // Use trim to remove extra spaces
			}, 0);
			var required = '<?php echo cl_translate("Total percent: "); ?>';
			var b = `<b class='text-primary p-2 required-percent'>${required + total + '%'}</b>`;

			if ($('.required-percent').length > 0) {
				$('.required-percent').text(required + total + '%');
				if (total !== 100) {
					$('.required-percent').addClass('text-danger');
					$('.required-percent').removeClass('text-primary');
				} else {
					$('.required-percent').addClass('text-primary');
					$('.required-percent').removeClass('text-danger');
				}
			} else {
				$('.require-percent').append(b);
				if (total !== 100) {
					$('.required-percent').addClass('text-danger');
					$('.required-percent').removeClass('text-primary');
				} else {
					$('.required-percent').addClass('text-primary');
					$('.required-percent').removeClass('text-danger');
				}
			}
		})

	});
</script>