<?php
$id = $me['id'];
$sql = "SELECT * FROM cl_store WHERE user_id = $id";
$result = conn()->query($sql);
if ($result->num_rows > 0) {
    foreach ($result as $row) {
        $store_id[] = $row['id'];
    }
}
foreach ($store_id as $id) {
    $game_id = get_game_id($id);
    foreach ($game_id as $g) {
        $game[] = get_game_name($g);
        $store[] = get_store_name($id);
        $sql_game = "SELECT * FROM cl_game WHERE id = $g";
        $result_game = conn()->query(($sql_game));
        if ($result_game->num_rows > 0) {
            foreach ($result_game as $row_game) {
                $status[] = $row_game['status'];
                $expires_date[] = $row_game['expires_date'];
            }
        }
    }
}
?>

<div class="timeline-container" data-app="store">
    <div class="timeline-header" data-el="tl-header">
        <div class="timeline-header__botline">
            <div class="lp">
                <div class="nav-link-holder">
                    <a>
                        <?php echo cl_translate("Store"); ?>
                    </a>
                </div>
            </div>
            <div class="cp">
                <a href="<?php echo cl_link('/'); ?>">
                    <img src="{%config site_logo%}" alt="Logo">
                </a>
            </div>
            <div class="rp">
                <div class="nav-link-holder">
                    <span class="go-back" onclick="SMColibri.go_back();">
                        <?php echo cl_ficon('arrow_back'); ?>
                    </span>
                </div>
            </div>
        </div>
    </div>
    <?php //if (not_empty($cl['is_admin'])): 
    ?>
    <!-- Add translate in json -->
    <form action="" class="p-2">
        <h2 class="text-center text-success">
            <?php echo cl_translate("Add Store"); ?>
        </h2>
        <div class="d-flex align-items-center justify-content-center">
            <label for="store" class="col-2 text-end"><?php echo cl_translate("Store Name:"); ?></label>
            <div class="require-store col-9">
                <input type="text" id="store" class="p-2 m-2 form-control" required>
            </div>
        </div>
        <div class="d-flex align-items-center justify-content-center">
            <label for="address" class="col-2 text-end"><?php echo cl_translate("Address:"); ?></label>
            <div class="require-address col-9">
                <input type="text" id="address" class="p-2 m-2 form-control" required>
            </div>
        </div>
        <div class="d-flex align-items-center justify-content-center">
            <label for="city" class="col-2 text-end"><?php echo cl_translate("City:"); ?></label>
            <div class="require-city col-9">
                <input name="city" id="city" class="form-control m-2 p-2" required>
            </div>
        </div>
        <div class="d-flex align-items-center justify-content-center">
            <label for="phone" class="col-2 text-end"><?php echo cl_translate("Phone:"); ?></label>
            <div class="require-phone col-9">
                <input name="phone" id="phone" class="form-control m-2 p-2" required>
            </div>
        </div>
        <div class="d-flex align-items-center justify-content-center">
            <label for="mail" class="col-2 text-end"><?php echo cl_translate("Mail:"); ?></label>
            <div class="require-mail col-9">
                <input name="mail" id="mail" class="form-control m-2 p-2">
            </div>
        </div>

        <div class="text-center">
            <button class="col-2 p-2 m-2 text-white btn-success border-0 rounded-pill add-store"><?php echo cl_translate("Add store"); ?></button>
            <button class="col-2 p-2 m-2 text-white btn-danger border-0 rounded-pill managed-store"><?php echo cl_translate("Managed"); ?></button>
        </div>

    </form>
    <?php //endif; 
    ?>
    <center>
        <div class="table-responsive-md u-datatable p-2">
            <table id="storeTable">
                <thead>
                    <tr class="text-uppercase font-size-1">
                        <th scope="col" class="font-weight-medium">
                            <div class="d-flex justify-content-center align-items-center">
                                Store
                                <div class="ml-2">
                                    <span class="fas fa-angle-up u-datatable__thead-icon"></span>
                                    <span class="fas fa-angle-down u-datatable__thead-icon"></span>
                                </div>
                            </div>
                        </th>
                        <th scope="col" class="font-weight-medium">
                            <div class="d-flex justify-content-center align-items-center">
                                Event
                                <div class="ml-2">
                                    <span class="fas fa-angle-up u-datatable__thead-icon"></span>
                                    <span class="fas fa-angle-down u-datatable__thead-icon"></span>
                                </div>
                            </div>
                        </th>
                        <th scope="col" class="font-weight-medium">
                            <div class="d-flex justify-content-center align-items-center">
                                Status
                                <div class="ml-2">
                                    <span class="fas fa-angle-up u-datatable__thead-icon"></span>
                                    <span class="fas fa-angle-down u-datatable__thead-icon"></span>
                                </div>
                            </div>
                        </th>
                        <th scope="col" class="font-weight-medium">
                            <div class="d-flex justify-content-center align-items-center">
                                Date
                                <div class="ml-2">
                                    <span class="fas fa-angle-up u-datatable__thead-icon"></span>
                                    <span class="fas fa-angle-down u-datatable__thead-icon"></span>
                                </div>
                            </div>
                        </th>
                        <th scope="col" class="font-weight-medium">
                            <div class="d-flex justify-content-center align-items-center">
                                Attr
                                <div class="ml-2">
                                    <span class="fas fa-angle-up u-datatable__thead-icon"></span>
                                    <span class="fas fa-angle-down u-datatable__thead-icon"></span>
                                </div>
                            </div>
                        </th>
                    </tr>
                </thead>
                <tbody class="font-size-1">
                    <?php for ($i = 0; $i < count($game); $i++) { ?>
                        <tr>
                            <td class="align-middle text-dark font-weight-normal"><?= $store[$i] ?></td>
                            <td>
                                <span><?= $game[$i] ?></span>
                            </td>
                            <td class="align-middle <?= ($status[$i] == 1) ? 'text-primary' : 'text-secondary' ?>"><?= ($status[$i] == 1) ? 'Publish' : 'Draft' ?></td>
                            <td class="align-middle text-secondary"><?= $expires_date[$i] ?></td>
                            <td class="align-middle text-danger">Rejected</td>
                        </tr>
                    <?php } ?>

                </tbody>
            </table>
        </div>
    </center>
</div>
<?php echo cl_template('store/scripts/app_master_script'); ?>
<script src="https://cdn.datatables.net/v/dt/dt-2.1.4/datatables.min.js"></script>
<script>
    new DataTable('#storeTable');
</script>