<style>
	.timeline-container-wrapper {
		max-width: 1000px !important;
		min-width: 1000px !important;
	}
</style>
<div class="table-responsive-md u-datatable px-2" style="padding-bottom: 64px">
	<table id="kycTable">
		<thead>
			<tr class="text-uppercase font-size-1">
				<!-- <th class="font-weight-medium">
					<div class="d-flex justify-content-center align-items-center">
						<input type="checkbox" name="" class="form-check-input" id="selectAll">
					</div>
				</th> -->
				<th scope="col" class="font-weight-medium">
					<div class="d-flex justify-content-center align-items-center">
						<?= cl_translate('User') ?>
						<div class="ml-2">
						</div>
					</div>
				</th>
				<th scope="col" class="font-weight-medium">
					<div class="d-flex justify-content-center align-items-center">
						<?= cl_translate('Age') ?>
						<div class="ml-2">
						</div>
					</div>
				</th>
				<th scope="col" class="font-weight-medium">
					<div class="d-flex justify-content-center align-items-center">
						<?= cl_translate('Address') ?>
						<div class="ml-2">
						</div>
					</div>
				</th>
				<th scope="col" class="font-weight-medium">
					<div class="d-flex justify-content-center align-items-center">
						<?= cl_translate('Phone') ?>
						<div class="ml-2">
						</div>
					</div>
				</th>
				<th scope="col" class="font-weight-medium">
					<div class="d-flex justify-content-center align-items-center">
						<?= cl_translate('Img') ?>
						<div class="ml-2">
						</div>
					</div>
				</th>
				<th scope="col" class="font-weight-medium">
					<div class="d-flex justify-content-center align-items-center">
						<?= cl_translate('ID card') ?>
						<div class="ml-2">
						</div>
					</div>
				</th>
				<th scope="col" class="font-weight-medium">
					<div class="d-flex justify-content-center align-items-center">
						<?= cl_translate('Created') ?>
						<div class="ml-2">
						</div>
					</div>
				</th>
				<th scope="col" class="font-weight-medium">
					<div class="d-flex justify-content-center align-items-center">
						<?= cl_translate('Verified') ?>
						<div class="ml-2">
						</div>
					</div>
				</th>
				<th scope="col" class="font-weight-medium">
					<div class="d-flex justify-content-center align-items-center">
						<?= cl_translate('Action') ?>
						<div class="ml-2">
						</div>
					</div>
				</th>
			</tr>
		</thead>
		<tbody>
			<?php if (count(get_kyc()) > 0) { ?>
				<?php foreach (get_kyc() as $kyc) {
					$k = json_decode($kyc['kyc'], true);
					$name = $k['info']['name'];
					$birth = new DateTime($k['info']['birth']);
					$now = new DateTime();
					$age = $now->diff($birth)->y;
					$address = $k['info']['address'];
					$phone = $k['info']['phone'];
					$img = $k['img'];
				?>

					<tr class="tr text-center">
						<!-- <td>
							<input type="checkbox" class="form-check-input select" data-prize="<?= $prize['id'] ?>" data-id="<?= $me['id'] ?>" data-store="<?= $prize['store_id'] ?>" data-game="<?= $prize['game_id'] ?>">
						</td> -->
						<td>
							<?= $name ?>
						</td>
						<td class="text-center">
							<?= $age ?>
						</td>
						<td>
							<?= $address ?>
						</td>
						<td class="text-center">
							<?= $phone ?>
						</td>
						<td class="text-success">
							<a href="<?= cl_get_media($img[0]) ?>" class="fbox-media" data-fancybox="fbox-media-8">
								<img src="<?= cl_get_media($img[0]) ?>" width="100px" alt="" srcset="">
							</a>
						</td>
						<td>
							<div>
								<a href="<?= cl_get_media($img[1]) ?>" class="fbox-media" data-fancybox="fbox-media-8">
									<img src="<?= cl_get_media($img[1]) ?>" width="100px" alt="" srcset="">
								</a>
								<a href="<?= cl_get_media($img[2]) ?>" class="fbox-media" data-fancybox="fbox-media-8">
									<img src="<?= cl_get_media($img[2]) ?>" width="100px" alt="" srcset="">
								</a>

							</div>
						</td>
						<td class="text-primary">
							<?= ($kyc['created_at']) ? date('Y-m-d', strtotime($kyc['created_at']))  : '' ?>
						</td>
						<td class="text-success verify">
							<?= ($kyc['verified_at']) ? date('Y-m-d', strtotime($kyc['verified_at']))  : '' ?>
						</td>
						<td>
							<div class="d-flex justify-content-center">
								<button class="verified px-3 py-2 me-1 border-0 rounded-3 btn-success <?= ($kyc['verified_at']) ? 'd-none'  : '' ?>" data-user="<?= $kyc['user_id'] ?>" data-kyc="<?= $kyc['id'] ?>"><?php echo cl_icon("person-fill-check"); ?></button>
								<button class="verified-delete px-3 py-2 border-0 rounded-3 btn-danger" data-kyc="<?= $kyc['id'] ?>"><i class="fas fs-5 fa-trash-alt text-white"></i></button>
							</div>
						</td>
					</tr>
				<?php } ?>
			<?php } ?>
		</tbody>
	</table>
</div>