<?php
$id = $me['id'];
$sql = "SELECT * FROM cl_store WHERE user_id = $id ORDER BY id DESC";
$result = conn()->query($sql);
?>
<script type="module" src="{%config theme_url%}/statics/js/index.js?v={%config update_date%}"></script>

<div class="timeline-container" data-app="spin">
	<div class="timeline-header" data-el="tl-header">
		<div class="timeline-header__botline">
			<div class="lp">
				<div class="nav-link-holder">
					<a href="<?php echo cl_link("spin"); ?>" data-spa="true">
						<?php echo cl_translate("Spin"); ?>
					</a>
				</div>
			</div>
			<div class="cp">
				<a href="<?php echo cl_link('/'); ?>">
					<img src="{%config site_logo%}" alt="Logo">
				</a>
			</div>
			<div class="rp">
				<div class="nav-link-holder">
					<span class="go-back" onclick="SMColibri.go_back();">
						<?php echo cl_ficon('arrow_back'); ?>
					</span>
				</div>
			</div>
		</div>
	</div>
	<center>
		<div class="timeline-game">
			<!--  -->
			<!--  -->
			<h2 class="p-2 m-2"><?php echo cl_translate("Spin game"); ?></h2>
			<?php
			if ($result->num_rows > 1) {
			?>
				<ul class="nav nav-tabs" id="myTab" role="tablist">
					<?php
					if ($result->num_rows > 1) {
						$firstRow = true; // Flag to track the first row
						$secondRow = false; // Flag to track the second row
						$currentTab = ''; // Variable to store the currently active tab
						foreach ($result as $row) {
					?>
							<li class="nav-item" role="presentation">
								<button class="nav-link <?php echo $firstRow ? 'active' : ($secondRow ? 'active' : ''); ?>" id="<?= $row['shop_name'] ?>-tab" data-bs-toggle="tab" data-bs-target="#<?= $row['shop_name'] ?>" type="button" role="tab" aria-controls="<?= $row['shop_name'] ?>" aria-selected="true" onclick="setActiveTab('<?= $row['shop_name'] ?>')" data-tab="<?= $row['shop_name'] ?>"><?= $row['shop_name'] ?></button>
							</li>
					<?php
							$firstRow = false; // Set flag to false after the first row
							if ($secondRow) { // Reset the second row flag after it's been used
								$secondRow = false;
							}
						}
					} ?>
				</ul>
				<div class="tab-content" id="myTabContent">
					<?php
					if ($result->num_rows > 1) {
						$firstRow = true; // Flag to track the first row
						$secondRow = false; // Flag to track the second row
						$currentTab = ''; // Variable to store the currently active tab
						foreach ($result as $row) {
							$store_id[] = $row['id'];
							$s = $row['id'];
							$name[] = $row['shop_name'];
					?>
							<div class="tab-pane fade <?php echo $firstRow ? 'show active' : ($secondRow ? 'show active' : ''); ?>" id="<?= $row['shop_name'] ?>" role="tabpanel" aria-labelledby="<?= $row['shop_name'] ?>-tab">
								<!-- Content for each tab -->
								<h2><?= $row['shop_name'] ?></h2>
								<div class="d-flex align-items-center justify-content-center">
									<label for="themes" class="col-2 text-end"><?php echo cl_translate("Select Game:"); ?></label>
									<div class="col-9">
										<select class="form-select store-api m-2 p-2" id="themes"></select>
									</div>
								</div>
								<div class="gui-wrapper bg-success text-white rounded-3 p-2 m-2">
									<div class="justify-content-center">
										<?php
										$sql_game = "SELECT * FROM cl_game WHERE store_id = $s AND status = 1";
										$result_game = conn()->query($sql_game);
										if ($result_game->num_rows > 0) {
											foreach ($result_game as $row_game) {
												$props[] = $row_game['props'];
												$themes[] = $row_game['themes'];
												$game_id[] = $row_game['id'];
												$attr = json_decode($row_game['props'], true);
												$value = choose_prize($attr);
												$prizes[] = $value['value'];
											}
										}
										$prop = implode('|', $props);
										$theme = implode('|', $themes);
										$prize = implode('|', $prizes);
										$names = implode('|', $name);
										$store_ids = implode('|', $store_id);
										$game_ids = implode('|', $game_id);
										?>
										<input type="hidden" name="" id="propsWheel" data-name="<?= $names ?>" data-user="<?= $me['id'] ?>" data-store="<?= $store_ids ?>" data-game="<?= $game_ids ?>" data-prop='<?= $prop ?>' data-themes='<?= $theme ?>'>
										<input type="hidden" id="tokenApi" value="<?= get_random() . $prize . get_random() ?>">
										<!-- else -->
										<?php
										$s = $row['id'];
										$sql_game = "SELECT * FROM cl_game WHERE store_id = $s AND status = 1";
										$result_game = conn()->query($sql_game);
										if ($result_game->num_rows > 0) {
											foreach ($result_game as $row_game) {
												$attr = json_decode($row_game['props'], true);
												$value = choose_prize($attr);
												$prize = $value['value'];
										?>
												<h3 class="p-2 m-2"><?= cl_translate('You choosing') . ' ' . $row['shop_name'] ?></h3>
												<input type="hidden" name="" id="propsWheel" data-name="<?= $row['shop_name'] ?>" data-user="<?= $me['id'] ?>" data-store="<?= $s ?>" data-game="<?= $row_game['id'] ?>" data-prop='<?= $row_game['props'] ?>' data-themes='<?= $row_game['themes'] ?>'>
												<input type="hidden" id="tokenApi" value="<?= get_random_number() . $prize . get_random_number() ?>">
											<?php } ?>
										<?php } ?>
									</div>
								</div>
								<div class="wheel-wrapper">
								</div> <!-- Add more content as needed -->
							</div>
					<?php
							$firstRow = false; // Set flag to false after the first row
							if ($secondRow) { // Reset the second row flag after it's been used
								$secondRow = false;
							}
						}
					} ?>
				</div>
				<script>
					function setActiveTab(shopName) {
						// Remove active class from all tabs
						document.querySelectorAll('.nav-link').forEach(link => {
							link.classList.remove('active');
						});

						// Add active class to the clicked tab
						document.getElementById(shopName + '-tab').classList.add('active');

						// Update the current tab variable
						currentTab = shopName;

						// Hide all tab panes except the first one
						document.querySelectorAll('.tab-pane').forEach(pane => {
							pane.classList.remove('show', 'active');
						});
						document.getElementById(shopName).classList.add('show', 'active');
						console.log(shopName);return
						// redirect
						window.location.href = '?tab=' + shopName;
						const urlParams = new URLSearchParams(window.location.search);
						const selectedTab = urlParams.get('tab');
						if (selectedTab) {
							// Find the corresponding tab and activate it
							const tabButton = document.getElementById(selectedTab + '-tab');
							if (tabButton) {
								tabButton.click();
							}
						}
					}
				</script>
			<?php } else { ?>
				<?php
				foreach ($result as $row) {
					$s = $row['id'];
				}
				$sql_game = "SELECT * FROM cl_game WHERE store_id = $s AND status = 1";
				$result_game = conn()->query($sql_game);
				if ($result_game->num_rows > 0) {
					foreach ($result_game as $row_game) {
						$attr = json_decode($row_game['props'], true);
						$value = choose_prize($attr);
						$prize = $value['value'];
				?>

						<input type="hidden" name="" id="propsWheel" data-name="<?= $row['shop_name'] ?>" data-user="<?= $me['id'] ?>" data-store="<?= $s ?>" data-game="<?= $row_game['id'] ?>" data-prop='<?= $row_game['props'] ?>' data-themes='<?= $row_game['themes'] ?>'>
						<input type="hidden" id="tokenApi" value="<?= get_random_number() . $prize . get_random_number() ?>">
						<div class="d-none align-items-center justify-content-center">
							<label for="themes" class="col-2 text-end"><?php echo cl_translate("Select Game:"); ?></label>
							<div class="col-9">
								<select class="form-select store-api m-2 p-2" id="themes"></select>
							</div>
						</div>
						<h3 class="p-2 m-2 rounded-2 bg-success text-white"><?= cl_translate('Welcome to store') . ' ' . $row['shop_name'] ?></h3>
						<div class="wheel-wrapper">
						<?php } ?>
					<?php } ?>
				<?php } ?>
						</div>
						<div class="text-center">
							<button id="spin" class="col-4 spin p-2 m-2 btn-primary rounded-2">
								<span class="fs-4">Spin</span>
							</button>
						</div>
		</div>
	</center>
</div>
<?php echo cl_template('subscriptions/scripts/app_master_script'); ?>