<div class="timeline-container" data-app="subscriptions">
	<div class="timeline-header" data-el="tl-header">
		<div class="timeline-header__botline">
			<div class="lp">
				<div class="nav-link-holder">
					<a href="<?php echo cl_link("subscriptions"); ?>" data-spa="true">
						<?php echo cl_translate("Subscriptions"); ?>
					</a>
				</div>
			</div>
			<div class="cp">
				<a href="<?php echo cl_link('/'); ?>">
					<img src="{%config site_logo%}" alt="Logo">
				</a>
			</div>
			<div class="rp">
				<div class="nav-link-holder">
					<span class="go-back" onclick="SMColibri.go_back();">
						<?php echo cl_ficon('arrow_back'); ?>
					</span>
				</div>
			</div>
		</div>
	</div>
	<center>
		<div class="timeline-game">
			<!--  -->
			<!--  -->
			<h2 class="p-2 m-2"><?php echo cl_translate("Spin game"); ?></h2>
			<div class="d-none justify-content-center align-items-center">
				<label for="selectStore" class="col-2"><?php echo cl_translate("Select store:"); ?></label>
				<div class="col-9">
					<select name="selectStore" id="selectStore" class="m-2 form-select col-9">
						<option value=""><?php echo cl_translate("Select store"); ?></option>
						<?php
						if ($result->num_rows > 0) {
							foreach ($result as $row) {
								$store_id[] = $row['id'];
								$name[] = $row['shop_name'];
						?>
								<option value=" <?= $row['id'] ?>"><?= $row['shop_name'] ?></option>
							<?php } ?>
						<?php } ?>
					</select>
				</div>
			</div>
			<div class="d-flex align-items-center justify-content-center">
				<?php
				if ($result->num_rows > 0) {
				?>
					<label for="themes" style="width:27%" class="text-end"><?php echo cl_translate("Select store and game:"); ?></label>
					<div class="col-8">
						<select class="form-select store-api m-2 p-2" id="themes"></select>
					<?php } else { ?>
						<h4 value="0"><?php echo cl_translate("No event available, try to add store and event first"); ?></h4>
					<?php } ?>

					</div>
			</div>
		</div>
	<?php else: ?>
		<div class="timeline-placeholder">
			<div class="icon">
				<div class="icon__bg">
					<?php echo cl_ficon('person_tag'); ?>
				</div>
			</div>
			<div class="wheel-wrapper"></div>
			<?php
			if ($result->num_rows > 0) { ?>
				<div class="text-center">
					<button id="spin" class="col-4 spin p-2 m-2 btn-primary rounded-pill">
						<span class="fs-4">Spin</span>
					</button>
				</div>
			<?php } ?>

		</div>
	<?php endif; ?>
</div>