<script>
	"use strict";

	$(document).ready(function($) {

		$('.claim').on('click', function() {
			var id = $(this).attr('data-id');
			var store = $(this).attr('data-store');
			var game = $(this).attr('data-game');
			Swal.fire({
				title: "<?php echo cl_translate("Reward"); ?>",
				text: "<?php echo cl_translate("Confirm prize award for this customer?"); ?>",
				icon: "question",
				allowOutsideClick: false,
				showConfirmButton: true,
				showCancelButton: true,
				confirmButtonText: "<?php echo cl_translate("Ok"); ?>",
				cancelButtonText: "<?php echo cl_translate("Cancel"); ?>",
				onBeforeOpen: () => {
					Swal.showLoading();
				},
			}).then((response) => {
				if (response.isConfirmed) {
					$.ajax({
						url: '<?php echo cl_link("native_api/manager/claim"); ?>',
						type: 'POST',
						data: {
							id: id,
							store: store,
							game: game,
						},
						success: function(result) {
							console.log(result);
						}
					})
				}
			})
		})
	});
</script>