<div class="notifications-list__item" data-list-item="<?php echo ($cl['li']['id']); ?>">
	<div class="notif-data">
		<div class="notifications-list__item-avatar">
			<a href="<?php echo ($cl['li']['user_url']); ?>" data-spa="true" class="block-link">
				<div class="user-avatar">
					<img src="<?php echo ($cl['li']['avatar']); ?>" alt="Avatar">
				</div>
			</a>
		</div>
		<div class="notifications-list__item-data">
			<div class="notifications-data">
				<div class="notifications-data__body <?= ($cl['li']['subject'] == 'ticket' ? 'redirect' : '') ?>" id="<?= ($cl['li']['subject'] == 'ticket' ? 'redirect' : '') ?>">
					<a href="<?php echo ($cl['li']['url']); ?>" data-spa="">
						<div class="notifications-data__topline">
							<span class="user-name-holder">
								<span class="user-name-holder__name">
									<?php echo $cl['li']['name']; ?>
								</span>

								<?php if ($cl['li']['verified'] == '1'): ?>
									<span class="user-name-holder__badge">
										<?php echo cl_icon("verified_user_badge"); ?>
									</span>
								<?php endif; ?>
							</span>
							<span class="<?php if ($cl['li']['status'] == '0') {
												echo ('unseen');
											}; ?>" style="color: #8a96a3;">
								<?php if ($cl['li']['subject'] == 'verified'): ?>
									<?php echo cl_translate('Your verification request has been accepted'); ?>
								<?php elseif ($cl['li']['subject'] == 'reply'): ?>
									<?php echo cl_translate('Replied to your post'); ?>
								<?php elseif ($cl['li']['subject'] == 'subscribe'): ?>
									<?php echo cl_translate('Started following you'); ?>
								<?php elseif ($cl['li']['subject'] == 'subscribe_request'): ?>
									<?php echo cl_translate('Wants to follow you'); ?>
								<?php elseif ($cl['li']['subject'] == 'subscribe_accept'): ?>
									<?php echo cl_translate('Accepted your follow request'); ?>
								<?php elseif ($cl['li']['subject'] == 'mention'): ?>
									<?php echo cl_translate('Mentioned you in a post'); ?>
								<?php elseif ($cl['li']['subject'] == 'like'): ?>
									<?php echo cl_translate('Liked your post'); ?>
								<?php elseif ($cl['li']['subject'] == 'repost'): ?>
									<?php echo cl_translate('Shared your publication'); ?>
								<?php elseif ($cl['li']['subject'] == 'visit'): ?>
									<?php echo cl_translate('Visited your profile'); ?>
								<?php elseif ($cl['li']['subject'] == 'ad_approval'): ?>
									<?php echo cl_translate('Your add has been approved'); ?>
								<?php elseif ($cl['li']['subject'] == 'content_subscription'): ?>
									<?php echo cl_translate('Subscribed to your content'); ?>
									<!-- add notify event -->
								<?php elseif ($cl['li']['subject'] == 'event'): ?>
									<?php echo cl_translate('Create new event with store <b class="text-dark">' . $cl['li']['game'] . '</b>. Contact <b class="text-dark">' . $cl['li']['name'] . '</b> to get ticket'); ?>
								<?php elseif ($cl['li']['subject'] == 'buy'): ?>
									<?php echo cl_translate('You buy ') . '<b class="text-primary">' . $cl['li']['product'] . '</b>' . cl_translate(' at ') . '<b class="text-dark">' . $cl['li']['game'] . '</b>'; ?>
								<?php elseif ($cl['li']['subject'] == 'prize'): ?>
									<?php echo cl_translate('Congratulation. You receive ') . '<b class="text-success">' . $cl['li']['prize'] . '</b>' . cl_translate(' from event ') . '<b class="text-primary">' . $cl['li']['game'] . '</b>' . cl_translate(' at ') . '<b class="text-dark">' . $cl['li']['product'] . '</b>'; ?>
								<?php elseif ($cl['li']['subject'] == 'ticket'): ?>
									<?php echo cl_translate('You have receive ') . '<b class="text-success">' . $cl['li']['ticket'] . '</b>' . cl_translate(' ticket from store ') . '<b class="text-dark">' . $cl['li']['game'] . '</b>' . cl_translate('. Spin now'); ?>
								<?php elseif ($cl['li']['subject'] == 'self'):
									$all = explode(',', $cl['li']['all_user']);
									foreach ($all as $u) {
										$username[] = get_user_by_id($u);
									}
									$all_user = implode(', ', $username);
								?>
									<?php echo cl_translate('You have send notifications after create an event to ') . "<b class='text-dark' style='line-height: 1.4;'>" . $all_user . "</b>";  ?>
									<!--  -->
								<?php elseif ($cl['li']['subject'] == 'wallet_local_receipt'): ?>
									<?php echo cl_translate('Transferred {@trans_amount@} to your wallet', array(
										"trans_amount" => cl_html_el("b", $cl['li']['json']["trans_amount"])
									)); ?>
								<?php endif; ?>
							</span>
						</div>
						<div class="notifications-data__midline">
							<span class="notif-time">
								<?php echo $cl['li']['time']; ?>
							</span>
						</div>
					</a>
				</div>
				<div class="notifications-data__ctrls">
					<div class="notif-ctrls">
						<div class="notif-ctrls__delete">
							<button type="button" class="btn-custom-icon col-red" onclick="SMColibri.PS.notifs.delete_notif(<?php echo ($cl['li']['id']); ?>);">
								<?php echo cl_ficon("delete"); ?>
							</button>
						</div>
					</div>
				</div>
			</div>
			<?php if ($cl['li']['subject'] == 'subscribe_request'): ?>
				<div class="notif-controls">
					<button onclick="SMColibri.PS.notifs.accept_follow(<?php echo $cl['li']['json']["follow_request_id"]; ?>, <?php echo ($cl['li']['id']); ?>);" class="btn btn-custom main-inline sm">
						<?php echo cl_translate("Accept request"); ?>
					</button>
				</div>
			<?php endif; ?>
		</div>
	</div>
</div>