<?php
$id = $me['id'];
$ticket = get_ticket_data($id);
if (count($ticket) > 0) {
	$ticket_id = $ticket['id'];
	$game_id = $ticket['game_id'];
	for ($t = 0; $t < count($game_id); $t++) {
		$store_id[] = get_store_event_id($game_id[$t]);
	}
	$number = $ticket['ticket'];
	$tickets = implode('|', $number);
}
$check_phone = cl_db_get_item(T_USERS, array('id' => $id))['phone'];
// var_dump($game_id);die;
?>
<script type="module" src="{%config theme_url%}/statics/js/index.js?v={%config update_date%}"></script>

<div class="timeline-container" data-app="spin">
	<div class="timeline-header" data-el="tl-header">
		<div class="timeline-header__botline">
			<div class="lp">
				<div class="nav-link-holder">
					<a href="<?php echo cl_link("spin"); ?>" data-spa="true">
						<?php echo cl_translate("Spin"); ?>
					</a>
				</div>
			</div>
			<div class="cp">
				<a href="<?php echo cl_link('/'); ?>">
					<img src="{%config site_logo%}" alt="Logo">
				</a>
			</div>
			<div class="rp">
				<div class="nav-link-holder">
					<span class="go-back" onclick="SMColibri.go_back();">
						<?php echo cl_ficon('arrow_back'); ?>
					</span>
				</div>
			</div>
		</div>
	</div>
	<center>
		<div class="timeline-game">
			<!--  -->
			<!--  -->
			<h1 class="p-2 m-2 text-success"><?php echo cl_translate("Spin game"); ?></h1>
			<?php ?>

			<div class="d-flex align-items-center justify-content-center">
				<?php if (@count($ticket['id']) > 0) { ?>
					<label for="themes" style="width:27%" class="text-end"><?php echo cl_translate("Select store and game:"); ?></label>
					<div class="col-8">
						<select class="form-select store-api m-2 p-2" id="themes"></select>
					</div>
				<?php } else { ?>
					<h2 class="text-danger" id="noWheel"><?php echo cl_translate("Buy or contact store to get ticket"); ?></h2>
				<?php } ?>
			</div>
			<div class="gui-wrapper bg-success text-white rounded-pill p-2 m-2">
				<div class="justify-content-center">
					<?php
					if (@count($ticket['id']) > 1) {
						foreach ($game_id as $s) {
							$sql_game = "SELECT * FROM cl_game WHERE id = $s AND status = 1";
							$result_game = conn()->query($sql_game);
							// var_dump($sql_game);die;
							if ($result_game->num_rows > 0) {
								foreach ($result_game as $row_game) {
									if ($result_game->num_rows > 0) {
										$props[] = $row_game['props'];
										$themes[] = $row_game['themes'];
										$game_id_2[] = $row_game['id'];
										$events[] = $row_game['game_name'];
										$attr = json_decode($row_game['props'], true);
										$value = choose_prize($attr);
										$prizes[] = $value['value'];
										$store_id_game[] = $row_game['store_id'];
										// $store_id[] = $row['shop_name'];
										$name_game[] = get_store_name($row_game['store_id']);
									}
								}
							}
						}
						$prop = implode('|', $props);
						$theme = implode('|', $themes);
						$prize = implode('|', $prizes);
						$game_ids = implode('|', $game_id_2);
						$event = implode('|', $events);
						if (@$store_id_game) {
							$names = implode('|', $name_game);
							$store_ids = implode('|', $store_id_game);
						} else {
							$names = implode('|', $name);
							$store_ids = implode('|', $store_id);
						}
					?>
						<h3 class="p-2 m-2"><?= cl_translate('You choosing Store') ?> <span class="store-name fs-3"></span></h3>
						<input type="hidden" name="" id="propsWheel" data-name="<?= $names ?>" data-event="<?= $event ?>" data-user="<?= $me['id'] ?>" data-store="<?= $store_ids ?>" data-game="<?= $game_ids ?>" data-prop='<?= $prop ?>' data-themes='<?= $theme ?>' data-key="<?= get_random() . $tickets . get_random() ?>">
						<input type="hidden" id="tokenApi" value="<?= get_random() . $prize . get_random() ?>">
						<!-- else -->
						<?php } elseif (@count($ticket['id']) > 0) {
						$s = $game_id[0];
						$ticket = $number[0];
						$store_id = get_store_game_id($s);
						$store_name = get_store_name($store_id);
						$sql_game = "SELECT * FROM cl_game WHERE id = $s AND status = 1";
						$result_game = conn()->query($sql_game);
						if ($result_game->num_rows > 0) {
							foreach ($result_game as $row_game) {
								$attr = json_decode($row_game['props'], true);
								$value = choose_prize($attr);
								$prize = $value['value'];
						?>
								<h3 class="p-2 m-2"><?= cl_translate('You choosing') . ' ' . $store_name ?></h3>
								<input type="hidden" name="" id="propsWheel" data-name="<?= $store_name ?>" data-user="<?= $me['id'] ?>" data-store="<?= $store_id ?>" data-game="<?= $row_game['id'] ?>" data-prop='<?= $row_game['props'] ?>' data-themes='<?= $row_game['themes'] ?>' data-key='<?= get_random_number() . $ticket . get_random_number() ?>'>
								<input type="hidden" id="tokenApi" value="<?= get_random_number() . $prize . get_random_number() ?>">
							<?php } ?>
						<?php } ?>
					<?php } ?>
				</div>
			</div>
			<?php if (@count($ticket['id']) > 0) { ?>
				<div class="wheel-wrapper"></div>
				<div class="text-center">
					<button id="spin_prize" class="col-4 spin p-2 m-2 btn-primary rounded-pill">
						<span class="fs-4">Spin</span>
					</button>
				</div>
				<?php } else {
				if (!$check_phone) { ?>
					<?= cl_template('spin_prize/includes/phone'); ?>
				<?php } ?>
			<?php } ?>
		</div>
	</center>
</div>
<?php echo cl_template('spin_prize/scripts/app_master_script'); ?>